server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: zipkin-sleuth
          uri: https://github.com/miguel1994-bot/microservicios-tutorial
          search-paths: config-data 
  application:
    name: config-service  
